# Generated by Django 6.0.3 on 2026-05-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='socios_fotos'),
        ),
    ]
