# Generated by Django 6.0.3 on 2026-05-05 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duracion_meses', models.IntegerField()),
                ('beneficios', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gimnasio.membresia'),
        ),
    ]
